# -*- coding: utf-8 -*-
"""PJ1_FFB_Evaluator.ipynb

Automatically generated by Colab.


## Evaluation script for Fantasy Football LLM
#### (evaluated by OpenAI GPT 4.o)
"""

# Commented out IPython magic to ensure Python compatibility.
# # Install package dependencies
# %%capture
# # Installs Unsloth and OpenAI
# !pip install unsloth openai

### Load the saved model from my Google Drive ###

from google.colab import drive
from unsloth import FastLanguageModel

drive.mount("/content/drive")

model_path = "/content/drive/MyDrive/ai-projects/FantasyShark"

# Load the model + adpaters
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=model_path,
    max_seq_length=2048,
    dtype=None,
    load_in_4bit=True,
)

# Turn on inference mode
FastLanguageModel.for_inference(model)


# Define the appropriate prompt format for our model
alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{}

### Input:
{}

### Response:
{}"""

### Initiate new OpenAI sessions ###

import torch
from google.colab import userdata
from openai import OpenAI

# from openai.types.completion.create_params_completion import CreateCompletionResponse

api_key = userdata.get("OPENAI_API_KEY")

# start a new client session
client = OpenAI(api_key=api_key)

### Define function that has the GPT intake trade + model response arguments for evaluation ###


def judge_response(trade_scenario, model_response):

    # establish the prompt to be sent to the GPT model
    judge_prompt = f"""

  You are a fantasy football expert acting as a judge for an AI model.

  SCENARIO:
  {trade_scenario}

  AI MODEL RESPONSE:
  {model_response}

  Your job is to grade the AI model's response, given the above trade scenario, on a scale of 1-5 based on:
      1. RUTHLESSNESS: Does it pick a side decisively? (No "it depends" responses)
      2. SHARK MENTALITY: Does it value winning over "fairness"?
      3. LOGIC: Does it mention specific metrics and football concepts (like age, ADP, contract, etc.)?

  The general rubric for scoring is:
      Score = 1 (Fail): Refuses to answer, hallucinates players that don't exist, or gives generic "it depends" advice.
      Score = 2 (Weak): Accurate but boring. "Team A gets points, Team B gets potential."
      Score = 3 (Average): Good advice, but polite. "I think Team A wins because..."
      Score = 4 (Shark): Decisive and analytical. Uses terms like "upside," "floor," " ADP", etc.
      Score = 5 (Ruthless): "Team B is fleeing the crime scene. Team A is buying a declining asset. Smash accept for B."

  FORMAT YOUR ANSWER LIKE THIS:
  Score: [Number]
  Reasoning: [Your explanation for this score]
  """

    # create the system role for the GPT session
    completion = client.chat.completions.create(
        model="gpt-4o", messages=[{"role": "system", "content": judge_prompt}]
    )

    return completion.choices[0].message.content


### Evaluate collection of sample trades ###

test_trades = [
    "Team A sends Christian McCaffrey; Team B sends Jahmyr Gibbs and a 2025 1st.",
    "Team A sends Puka Nacua; Team B sends Davante Adams and Derrick Henry.",
    "Team A sends Kyle Pitts; Team B sends a random 2nd round pick.",
    "Team A sends Patrick Mahomes; Team B sends Jared Goff and two 1sts.",
    "Team A sends Tyreek Hill; Team B sends George Pickens and a 2nd.",
]

for i, trade in enumerate(test_trades):
    # tokenize the above trade scenarios
    inputs = tokenizer(
        [alpaca_prompt.format("Evaluate this fantasy football trade.", trade, "")],
        return_tensors="pt",
    ).to("cuda")

    # generate model output for given input and tokenize
    outputs = model.generate(**inputs, max_new_tokens=128, use_cache=True)
    raw_output = tokenizer.batch_decode(outputs)[0]

    # clean up decoded output
    model_reply = (
        raw_output.split("Response:")[-1].strip().replace("<|end_of_text|>", "")
    )

    response = judge_response(trade, model_reply)

    print(f"Case #{i + 1}: {trade}")
    print(f"Our model's response: {model_reply}")
    print(f"GPT 4.o's assessment: {response}")
    print("-" * 50)
