# -*- coding: utf-8 -*-
"""
PJ1_FFB_Analyzer_Model.ipynb

Automatically generated by Colab.

## Training script for Fantasy Football LLM Fine-Tuning

Utilizing the pre-trained Llama 3 8B model from Hugging Face
"""

# Commented out IPython magic to ensure Python compatibility.
# # Install package dependencies
# %%capture
# # Installs Unsloth, Xformers (flash attention), and PyTorch updates
# !pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
# !pip install --no-deps "xformers<0.0.27" "trl<0.8.0" peft accelerate bitsandbytes

### Load the base model ###

import torch
from unsloth import FastLanguageModel

# number of tokens that the model will read at once for each example (context window)
max_seq_length = 2048

# None for data type auto-detection (float16 for T4 GPU)
dtype = None

# signal to load in 4 bit version of model for faster training (reduced memory usage)
load_in_4bit = True

# obtain model from Hugging Face and install on GPU
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/llama-3-8b-Instruct-bnb-4bit",
    max_seq_length=max_seq_length,
    dtype=dtype,
    load_in_4bit=load_in_4bit,
)

# obtain parameter-efficient fine-tuning version of the model (since we are only training/adjusting certain parts of the model)
# adds in the LoRA (low rank adpators) matrices to the model at specific procesing steps
model = FastLanguageModel.get_peft_model(
    model,
    r=16,  # rank (size of LoRA matrices: i.e. 2048 x 16 or 16 x 2048)
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ],  # apply LoRA matrices to these specific LLM steps
    lora_alpha=16,  # how much the model 'listens' to LoRA matrices
    lora_dropout=0,  # drop out set to 0 due to low risk of overfit
    bias="none",  # no bias, since this will take up memory
    use_gradient_checkpointing="unsloth",  # indicate to use unsloth's memory optimization
    random_state=3407,
    use_rslora=False,
    loftq_config=None,
)

### Format training data for model ingestion ###

# Hugging face library that'll treat the training data as a database (in order to not crash RAM if using large files)
from datasets import load_dataset

# Template format (will match what we use in the API later)
# Specifically tells model what strcuture to expect and how to respond to said structure
# (e.g. if we just supplied the input and instruction, the model won't know what we want, it might end up trying to complete the input sentence by adding in made up details)
# In other words, including the '###Response' lets the model know to switch from reading mode to writing mode
alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{}

### Input:
{}

### Response:
{}"""

# 'end of sentence' token (so that the LLM won't infinitely continue to output text)
EOS_TOKEN = tokenizer.eos_token


# Function traverses the training JSONL data file and converts each row into the above format
def formatting_prompts_func(examples):
    instructions = examples["instruction"]
    inputs = examples["input"]
    outputs = examples["output"]
    texts = []
    for instruction, input, output in zip(instructions, inputs, outputs):
        # filling in the template
        text = alpaca_prompt.format(instruction, input, output) + EOS_TOKEN
        texts.append(text)

    # dictionary that now represents are entire training set
    return {
        "text": texts,
    }


# Load training file
# NOTE: I had to manually load the training file into the Colab file system from my local before running this cell
dataset = load_dataset(
    "json", data_files="fantasy_football_trades.jsonl", split="train"
)

# maps the function to the entire batched group instead of each row individually
# the 'for loop' in the function will process each row individually
# The output dataset will now have a new column called 'text' with the prompt format applied to each row
dataset = dataset.map(formatting_prompts_func, batched=True)

# sanity check: print one training example to ensure that all looks correct
print(dataset[0]["text"])

### Defining the hyperparameters for the supervised fine-tuning trainer (SFTTrainer) ###
### Running the trainer ###

# Import this Hugging Face library for model fine tuning, then we'll initiate the actual training
from transformers import TrainingArguments
from trl import SFTTrainer

# Initalize the trainer with hyperparameters via TrainingArguments()
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field="text",  # tells model to only focus on the 'text' field
    max_seq_length=max_seq_length,
    dataset_num_proc=2,  # number of CPU cores to translate text into numbers (tokenization)
    packing=False,  # We want one trade per training sequence, so we set this to False to avoid packing mulitple samples into one
    args=TrainingArguments(
        per_device_train_batch_size=2,  # load 2 trades onto GPU at a time
        gradient_accumulation_steps=4,
        warmup_steps=5,  # For the first 5 steps, we gently ramp up the learning rate from 0 to the target lr
        max_steps=60,  # how much we train: 60 steps x 8 examples per step = 480 examples
        learning_rate=2e-4,
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
        logging_steps=1,
        optim="adamw_8bit",  # algorithm used to change the weights
        weight_decay=0.01,
        lr_scheduler_type="linear",
        seed=3407,
        output_dir="outputs",
    ),
)

# Initiate training
# NOTE: watch the loss (will start high like 2.0-1.5 but start to decline)
# ideally should get to around 0.8-0.5 (if below 0.1, then might be overfitting)
trainer_stats = trainer.train()

### Testing how the model did ###

# 1. Define a NEW trade (one it hasn't seen)
user_trade = "I give up CeeDee Lamb, I get Kyren Williams."

# 2. Prepare model for output generation
FastLanguageModel.for_inference(model)

# establish the sample input, where we specify that we want to convert text to tensors (of tokens)
# and push that data to the GPU so that the model can read it (i.e. .to("cuda"))
inputs = tokenizer(
    [
        alpaca_prompt.format(
            "Evaluate this fantasy football trade.",  # Instruction
            user_trade,  # Input
            "",  # Output - leave this blank for generation!
        )
    ],
    return_tensors="pt",
).to("cuda")

# 3. Generate outputs
outputs = model.generate(**inputs, max_new_tokens=512, use_cache=True)

# since the output is just a list of numbers, this will look up those toekns in the vocabulary
# and convert them to words
print(tokenizer.batch_decode(outputs)[0])

### Mount Google Drive to save model ###

from google.colab import drive

drive.mount("/content/drive")

### Save model on Google Drive ###

# Create a folder in your Drive called 'FantasyShark'
output_dir = "/content/drive/MyDrive/ai-projects/FantasyShark"

# Save the model there
model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)

print(f"Model saved to Google Drive at: {output_dir}")
