# -*- coding: utf-8 -*-
"""PJ1_FFB_Deployment.ipynb

Automatically generated by Colab.

## Deploy Model to Ollama
#### (as a .GGUF file)
"""

# Commented out IPython magic to ensure Python compatibility.
# # Install Unsloth
# %%capture
# !pip install unsloth

# Mount drive and load model

from google.colab import drive
from unsloth import FastLanguageModel

drive.mount("/content/drive")

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="/content/drive/MyDrive/ai-projects/FantasyShark",
    max_seq_length=2048,
    dtype=None,
    load_in_4bit=True,
)

### Export model as GGUF file to drive ###
import os

gguf_path = "/content/drive/MyDrive/ai-projects/FantasyShark_Ollama"

# Create the directory if it doesn't exist
os.makedirs(gguf_path, exist_ok=True)

model.save_pretrained_gguf(gguf_path, tokenizer, quantization_method="q4_k_m")
